// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/Mangaba-Labs/ape-finance-api/database"
	"github.com/Mangaba-Labs/ape-finance-api/pkg/api/router"
	handler3 "github.com/Mangaba-Labs/ape-finance-api/pkg/domain/auth/handler"
	"github.com/Mangaba-Labs/ape-finance-api/pkg/domain/user/handler"
	"github.com/Mangaba-Labs/ape-finance-api/pkg/domain/user/repository"
	"github.com/Mangaba-Labs/ape-finance-api/pkg/domain/user/services"
)

// Injectors from wire.go:

func initializeServer() (*router.Server, error) {
	db, err := database.NewDatabase()
	if err != nil {
		return nil, err
	}
	repositoryRepository := repository.Repository{
		DB: db,
	}
	userService := services.NewUserService(repositoryRepository)
	handlerHandler := handler.NewUserHandler(userService)
	authHandler := handler3.NewAuthHandler(userService)
	server := router.NewServer(handlerHandler, authHandler)
	return server, nil
}
